import { infoTitles, type InfoPage } from "./store-data";

export function InfoContent({ page }: { page: Exclude<InfoPage, null> }) {
  return <div className="info-content"><p className="eyebrow">GHOST CLOSET / HELP</p><h2>{infoTitles[page]}</h2>
    {page === "shipping" && <><p>Available products are purchased on the linked official seller website. The seller confirms destination availability, delivery cost, taxes, tracking and the final delivery estimate before payment.</p><div className="info-rows"><div><span>DESTINATION</span><strong>CONFIRMED BY SELLER</strong></div><div><span>DELIVERY COST</span><strong>SHOWN BEFORE PAYMENT</strong></div><div><span>TRACKING</span><strong>PROVIDED WHEN AVAILABLE</strong></div></div></>}
    {page === "returns" && <><p>Returns, exchanges, refunds and warranty support are handled by the official seller that receives payment. Review that seller’s policy before ordering.</p><div className="info-rows"><div><span>01</span><strong>CHECK SELLER POLICY</strong></div><div><span>02</span><strong>CONTACT THE SELLER</strong></div><div><span>03</span><strong>KEEP TRACKING PROOF</strong></div></div></>}
    {page === "faq" && <div className="faq-list"><details open><summary>HOW DO I CHOOSE A SIZE?</summary><p>Use the fit notes on each product page. Supplier measurements must be confirmed on the official seller page before purchase.</p></details><details><summary>CAN I CHANGE MY ORDER?</summary><p>Contact the seller that accepted payment. Ghost Closet cannot edit orders placed on another website.</p></details><details><summary>HOW DO I TRACK DELIVERY?</summary><p>The official seller sends tracking when its delivery service supports it.</p></details><details><summary>DO YOU SHIP WORLDWIDE?</summary><p>Destination availability and rates are controlled by each official seller.</p></details></div>}
    {page === "contact" && <><p>For Ghost Closet product and sizing questions, contact support. Order, payment, delivery and refund questions must go to the seller that accepted payment.</p><a className="contact-link" href="mailto:store@ghostcloset.com">STORE@GHOSTCLOSET.COM ↗</a><p className="small-copy">RESPONSE TARGET: 1–2 BUSINESS DAYS<br />MONDAY–FRIDAY</p></>}
    {page === "terms" && <><p>Ghost Closet is currently a static editorial and affiliate-style storefront. Payment and delivery details are handled off-site by linked sellers. Ghost Closet does not collect card numbers, expiry dates, CVC codes or checkout addresses.</p><div className="info-rows"><div><span>STATUS</span><strong>DEMONSTRATION</strong></div><div><span>PAYMENTS</span><strong>HANDLED OFF-SITE</strong></div><div><span>LAST UPDATED</span><strong>JULY 2026</strong></div></div></>}
    {page === "privacy" && <><p>This static preview does not transmit newsletter addresses or payment details. Browser storage is used only for the local bag and saved-product state. Linked seller websites apply their own privacy policies.</p><div className="info-rows"><div><span>PAYMENT DATA</span><strong>NOT COLLECTED</strong></div><div><span>LOCAL STORAGE</span><strong>BAG + FAVORITES ONLY</strong></div><div><span>EXTERNAL SELLERS</span><strong>SEPARATE POLICIES</strong></div></div></>}
    {page === "cookies" && <><p>Ghost Closet does not currently set advertising or analytics cookies. The site stores the bag and favorites in local browser storage. External seller links may use cookies under their own policies.</p><div className="info-rows"><div><span>ANALYTICS COOKIES</span><strong>NOT ENABLED</strong></div><div><span>LOCAL STORAGE</span><strong>FUNCTIONAL ONLY</strong></div><div><span>SELLER SITES</span><strong>CHECK THEIR SETTINGS</strong></div></div></>}
  </div>;
}
